/* WELIT classroom 選擇競速：筆順方格、拆字配對、關聯詞填空、文言標記與情境材料共用即時回饋流程。 */
import { useEffect, useState } from 'react';
import { CarFront, Flag, Zap } from 'lucide-react';

function RadicalBuilder({ question, disabled, onAnswer }) {
  const [selected, setSelected] = useState([]);
  const [dragging, setDragging] = useState(null);
  const [dropActive, setDropActive] = useState(false);
  const [outcome, setOutcome] = useState(null);
  const [submitting, setSubmitting] = useState(false);
  useEffect(() => { setSelected([]); setDragging(null); setDropActive(false); setOutcome(null); setSubmitting(false); }, [question.prompt]);
  const togglePart = (index) => setSelected((items) => items.includes(index) ? items.filter((item) => item !== index) : [...items, index]);
  const addPart = (index) => setSelected((items) => items.includes(index) ? items : [...items, index]);
  const correct = question.correctParts.length === selected.length && question.correctParts.every((index) => selected.includes(index));
  const selectedParts = selected.map((index) => question.components[index]);
  const submit = () => { if (disabled || submitting || !selected.length) return; setSubmitting(true); setOutcome(correct ? 'success' : 'error'); window.setTimeout(() => onAnswer(correct, selectedParts.join('＋')), correct ? 620 : 360); };
  const dropPart = (event) => { event.preventDefault(); const droppedIndex = Number(event.dataTransfer.getData('text/plain')); if (Number.isInteger(droppedIndex)) addPart(droppedIndex); setDragging(null); setDropActive(false); };
  const statusText = outcome === 'success' ? `組字成功！「${question.targetCharacter}」已點亮。` : outcome === 'error' ? '這個組合還未正確，看看目標字的部首與部件。' : dragging !== null ? '放到「已選部件」區域，完成組字。' : '可拖曳部件到下方，或直接點擊部件選取。';
  return <section className={`radical-builder ${outcome || ''}`} aria-label={`把部件組合成「${question.targetCharacter}」字`}><div className={`radical-target ${outcome === 'success' ? 'celebrate' : ''}`}><span>目標漢字</span><b>{question.targetCharacter}</b><small>拖曳或點擊部件後，再確認組字。</small></div><div className="radical-workbench"><p>{question.prompt}</p><div className="component-bank">{question.components.map((part, index) => <button key={`${part}-${index}`} type="button" draggable={!disabled && !submitting} disabled={disabled || submitting} className={`${selected.includes(index) ? 'selected' : ''} ${dragging === index ? 'dragging' : ''} ${outcome === 'success' && question.correctParts.includes(index) ? 'correct-piece' : ''}`} onDragStart={(event) => { event.dataTransfer.setData('text/plain', String(index)); event.dataTransfer.effectAllowed = 'copy'; setDragging(index); }} onDragEnd={() => { setDragging(null); setDropActive(false); }} onClick={() => togglePart(index)}><span>部件 {String.fromCharCode(65 + index)}</span><b>{part}</b></button>)}</div><div className={`assembly-strip ${dropActive ? 'drop-active' : ''} ${outcome || ''}`} onDragOver={(event) => { event.preventDefault(); event.dataTransfer.dropEffect = 'copy'; }} onDragEnter={(event) => { event.preventDefault(); setDropActive(true); }} onDragLeave={() => setDropActive(false)} onDrop={dropPart}><span>已選部件</span><div>{selectedParts.length ? selectedParts.map((part, index) => <button type="button" key={`${part}-${index}`} onClick={() => togglePart(selected[index])} disabled={disabled || submitting} aria-label={`移除部件 ${part}`}>{part}</button>) : <em>拖曳部件到此處</em>}</div><button type="button" disabled={disabled || submitting || !selected.length} onClick={submit}>確認組字</button></div><p className={`radical-status ${outcome || ''}`} aria-live="polite">{statusText}</p></div></section>;
}

function ConnectorFill({ question, disabled, onAnswer, session }) {
  const [attempt, setAttempt] = useState(null);
  useEffect(() => setAttempt(null), [question.prompt]);
  const total = 15;
  const completed = session?.answers.length || 0;
  const correctSoFar = session?.answers.filter((answer) => answer.correct).length || 0;
  const progress = Math.min(100, ((session?.index || 0) + 1) / total * 100);
  const selectConnector = (option) => { if (disabled || attempt) return; const correct = option === question.options[question.answerIndex]; setAttempt({ option, correct }); window.setTimeout(() => onAnswer(correct, option), correct ? 520 : 760); };
  return <section className="connector-fill" aria-label="關聯詞填空"><div className="connector-progress"><div><span>關聯詞單元進度</span><b>第 {(session?.index || 0) + 1} / {total} 題</b></div><div className="connector-progress-track"><i style={{ width:`${progress}%` }}></i></div><small>已答對 {correctSoFar} 題・本題後將完成 {completed + 1} 題</small></div><section className="application-passage"><span>{question.studyLabel || '生活情境'}</span><p>{question.studyText}</p></section><p className="connector-task">{question.prompt}</p><div className="connector-sentence">{question.fillSentence.split('＿＿').map((part, index) => <span key={index}>{index > 0 && <b>＿＿</b>}{part}</span>)}</div><div className="connector-options">{question.options.map((option) => <button type="button" key={option} disabled={disabled || Boolean(attempt)} className={attempt ? (option === attempt.option ? (attempt.correct ? 'answer-correct' : 'answer-wrong') : option === question.options[question.answerIndex] && !attempt.correct ? 'reveal-correct' : '') : ''} onClick={() => selectConnector(option)}>{option}</button>)}</div>{attempt && <div className={`connector-feedback ${attempt.correct ? 'success' : 'error'}`} role="status"><b>{attempt.correct ? '答對了！' : '再想一想。'}</b><p>{attempt.correct ? question.explanation : <>正確答案是「{question.options[question.answerIndex]}」。{question.explanation}</>}</p></div>}</section>;
}

function ClassicalMarker({ question, disabled, onAnswer }) {
  const [selectedId, setSelectedId] = useState(null);
  useEffect(() => setSelectedId(null), [question.prompt]);
  const selected = question.markers.find((marker) => marker.id === selectedId);
  return <section className="classical-marker" aria-label="文言原文對譯標記"><p className="classical-instruction">先點擊原文詞語查看白話解釋，再確認你的重點標記。</p><div className="classical-text">{question.markers.map((marker) => <button key={marker.id} type="button" disabled={disabled} onClick={() => setSelectedId(marker.id)} className={selectedId === marker.id ? 'selected' : ''}>{marker.text}</button>)}</div><div className="gloss-panel">{selected ? <><span>白話提示</span><strong>「{selected.text}」</strong><p>{selected.gloss}</p></> : <><span>白話提示</span><p>請先點擊原文中的詞語。</p></>}</div><p className="classical-task">{question.prompt}</p><button type="button" className="mark-confirm" disabled={disabled || !selected} onClick={() => onAnswer(selected?.id === question.targetId, selected?.text)}>確認標記</button></section>;
}

export default function RaceEngine({ question, onAnswer, disabled, session }) {
  const isStrokeGrid = question.visualType === 'stroke-grid';
  const isRadicalBuild = question.visualType === 'radical-build';
  const isConnectorFill = question.visualType === 'connector-fill';
  const isClassicalMark = question.visualType === 'classical-mark';
  const isApplication = Boolean(question.studyText);
  return <div className={`engine race-engine ${isStrokeGrid ? 'stroke-race' : ''} ${isRadicalBuild ? 'radical-race' : ''} ${isConnectorFill ? 'connector-race' : ''} ${isClassicalMark ? 'classical-race' : ''} ${isApplication ? 'application-race' : ''}`}><div className="race-track" aria-hidden="true"><div className="finish-line"><Flag /></div><div className="race-car"><CarFront /></div><div className="speed-trail"></div></div><div className="engine-intro"><span className="engine-tag"><Zap size={15} /> 選擇競速</span><h2>{isRadicalBuild ? '組合正確部件！' : isConnectorFill ? '填入正確關聯詞！' : isClassicalMark ? '標記文言重點！' : '衝過終點線！'}</h2><p>{isRadicalBuild ? '點擊部件，再確認能否組成目標漢字。' : isConnectorFill ? '閱讀生活情境，找出最合適的句子關係。' : isClassicalMark ? '點擊原文詞語，查看白話提示後再確認。' : '選對答案，知識賽車立即加速。'}</p></div><div className={`question-card ${isStrokeGrid ? 'stroke-question-card' : ''} ${isApplication ? 'application-question-card' : ''} ${isRadicalBuild ? 'radical-question-card' : ''} ${isConnectorFill ? 'connector-question-card' : ''} ${isClassicalMark ? 'classical-question-card' : ''}`}><p className="question-number">{isStrokeGrid ? '筆順方格' : isRadicalBuild ? '拆字配對' : isConnectorFill ? '關聯詞填空' : isClassicalMark ? '原文對譯標記' : isApplication ? '情境任務' : 'QUICK PICK'}</p>{isStrokeGrid && <section className="stroke-grid-panel" aria-label={`「${question.character}」字的筆順方格`}><div className="hanzi-grid" aria-hidden="true"><i></i><i></i><b>{question.character}</b><span>第 {question.targetOrder} 筆</span></div><div className="stroke-task-copy"><strong>看清字形，再選筆畫次序。</strong><p>目標：找出「{question.character}」的第 <em>{question.targetOrder}</em> 筆。</p><div className="stroke-slots" aria-label="筆畫位置">{question.strokes.map((_, index) => <span key={index} className={index + 1 === question.targetOrder ? 'target' : index + 1 < question.targetOrder ? 'before' : ''}>{index + 1}</span>)}</div></div></section>}{isRadicalBuild && <RadicalBuilder question={question} disabled={disabled} onAnswer={onAnswer} />}{isConnectorFill && <ConnectorFill question={question} disabled={disabled} onAnswer={onAnswer} session={session} />}{isClassicalMark && <ClassicalMarker question={question} disabled={disabled} onAnswer={onAnswer} />}{isApplication && !isConnectorFill && <section className="application-passage"><span>{question.studyLabel || '閱讀材料'}</span><p>{question.studyText}</p></section>}{!isRadicalBuild && !isConnectorFill && !isClassicalMark && <><h3>{question.prompt}</h3>{question.promptEn && <p className="question-translation">{question.promptEn}</p>}<div className="answer-grid">{question.options.map((option, index) => <button key={option} disabled={disabled} onClick={() => onAnswer(index === question.answerIndex, option)} className="answer-btn race-answer"><span>{String.fromCharCode(65 + index)}</span>{option}</button>)}</div></>}</div></div>;
}
