import { ArrowLeft, ChevronRight, Languages, LayoutDashboard, Sparkles, Swords } from 'lucide-react';
import { useEffect, useState } from 'react';
import englishCatalog from '../data/englishCatalog';
import { getEnglishQuestionBank } from '../data/questionBanks/english';
import { getEnglishPracticeLink } from '../data/catalogPracticeLinks';

const GRADES = ['P1', 'P2', 'P3', 'P4', 'P5', 'P6'];
const GRADE_LABELS = ['一', '二', '三', '四', '五', '六'];
const canBattle = (unit) => unit.questions.some((question) => Array.isArray(question.choices) && question.choices.length >= 2 && question.answer !== undefined);
function Brand() { return <div className="brand" aria-label="WelitQuest"><span className="brand-mark"><i></i><i></i><i></i><Sparkles size={24} /></span><span><b>Welit<span>Quest</span></b><small>小學課堂展示版</small></span></div>; }
function TopicCard({ unit, grade, completedUnits, onStart, activityMode }) { const progress = completedUnits[unit.id]; const completed = Math.min(Array.isArray(progress) ? progress.length : progress || 0, unit.questions.length); const link = getEnglishPracticeLink(grade, unit.id); const battleReady = canBattle(unit); const launchBattle = activityMode === 'team-battle' && battleReady; return <button className={`subject-topic-card english-topic-card-direct ${link?.kind || 'foundation'} ${launchBattle ? 'battle-ready-card' : ''}`} onClick={() => onStart(unit, launchBattle ? 'team-battle' : 'worksheet')}><div className="subject-topic-meta"><span>{launchBattle ? <><Swords size={14} /> 全班合力題組</> : link?.kind === 'reading' ? '閱讀題組' : link?.kind === 'consolidation' ? '句式整合' : link?.kind === 'foundation' ? '預備能力' : '核心課題'}</span><b>{unit.questions.length} 題</b></div><h3>{link?.topic || unit.area}</h3><p>{unit.title}・{unit.objective}</p><small>{launchBattle ? '全班合力開戰' : completed ? `${completed} 題已完成` : activityMode === 'team-battle' ? '這題需個別操作' : '開始練習'} <ChevronRight size={15} /></small></button>; }
export default function EnglishCatalog({ initialGrade = 'P1', onBack, onHome, completedUnits, onStartUnit }) { const [grade, setGrade] = useState(initialGrade); const [activityMode, setActivityMode] = useState('worksheet'); useEffect(() => setGrade(initialGrade), [initialGrade]); const catalog = englishCatalog[grade]; const bank = getEnglishQuestionBank(grade); const questionCount = bank.units.reduce((total, unit) => total + unit.questions.length, 0); const lowPrimary = ['P1', 'P2', 'P3'].includes(grade); return <main className="site-shell catalog-page unified-catalog-page english-unified-page"><header className="topbar"><Brand /><div className="topbar-right"><span className="demo-pill">英文・P1–P6</span><button className="text-button" onClick={onBack}><ArrowLeft size={17} /> 返回選科</button><button className="icon-button" onClick={onHome} aria-label="返回首頁"><LayoutDashboard size={20} /></button></div></header><section className="subject-catalog-hero english-hero"><div><span className="kicker"><Languages size={15} /> 英文課題</span><h1>{catalog.gradeLabel} 英文</h1><p>{catalog.focus}</p></div><strong>{questionCount} 題</strong></section><section className="catalog-workbench unified-workbench english-workbench"><aside className="catalog-grade-rail english-grade-rail"><span>年級</span>{GRADES.map((item, index) => <button className={grade === item ? 'active' : ''} onClick={() => { setGrade(item); setActivityMode('worksheet'); }} key={item}><b>{item}</b><small>小{GRADE_LABELS[index]}</small></button>)}</aside><div className="catalog-content unified-catalog-content"><div className="subject-grade-heading"><span>{grade}・課題與練習</span><h2>{activityMode === 'team-battle' ? 'Choose a team quest and defeat the monster.' : '選擇課題，直接開始練習。'}</h2></div>{lowPrimary && <section className="low-primary-battle-mode english"><div><span><Swords size={16} /> 低小課堂遊戲</span><b>一般互動或全班打怪獸</b><small>把可選答的英語題轉成全班討論與合力挑戰。</small></div><div><button className={activityMode === 'worksheet' ? 'active' : ''} onClick={() => setActivityMode('worksheet')}>一般互動</button><button className={activityMode === 'team-battle' ? 'active battle' : ''} onClick={() => setActivityMode('team-battle')}><Swords size={15} /> 全班打怪獸</button></div></section>}<section className="subject-topic-grid">{bank.units.map((unit) => <TopicCard key={unit.id} unit={unit} grade={grade} completedUnits={completedUnits} onStart={onStartUnit} activityMode={activityMode} />)}</section></div></section></main>; }
