import { ArrowLeft, BookOpen, ChevronRight, LayoutDashboard, PenLine, Sparkles, Swords } from 'lucide-react';
import { useEffect, useState } from 'react';
import chineseCatalog from '../data/chineseCatalog';
import { getChineseQuestionBank } from '../data/questionBanks/chinese';
import { getChinesePracticeLink } from '../data/catalogPracticeLinks';

const GRADES = ['P1', 'P2', 'P3', 'P4', 'P5', 'P6'];
const GRADE_LABELS = ['一', '二', '三', '四', '五', '六'];
const canBattle = (unit) => unit.questions.some((question) => (Array.isArray(question.choices) && question.choices.length >= 2 && question.answer !== undefined) || (Array.isArray(question.matches) && question.matches.length >= 2));
function Brand() { return <div className="brand" aria-label="WelitQuest"><span className="brand-mark"><i></i><i></i><i></i><Sparkles size={24} /></span><span><b>Welit<span>Quest</span></b><small>小學課堂展示版</small></span></div>; }
function TopicCard({ unit, grade, catalog, completedUnits, onStart, activityMode }) {
  const progress = completedUnits[unit.id]; const completed = Math.min(Array.isArray(progress) ? progress.length : progress || 0, unit.questions.length); const [strand, index] = getChinesePracticeLink(grade, unit.id) || [unit.area === '寫作' ? 'writing' : 'reading', 0]; const topic = catalog[strand]?.[index] || unit.title; const objective = unit.questions[0]?.learningObjective || '掌握本課題的中文學習重點。'; const Icon = strand === 'writing' ? PenLine : BookOpen; const battleReady = canBattle(unit); const launchBattle = activityMode === 'team-battle' && battleReady;
  return <button className={`subject-topic-card chinese-topic-card ${strand} ${launchBattle ? 'battle-ready-card' : ''}`} onClick={() => onStart(unit, launchBattle ? 'team-battle' : 'worksheet')}><div className="subject-topic-meta"><span>{launchBattle ? <><Swords size={14} /> 全班合力題組</> : <><Icon size={14} /> {strand === 'writing' ? '寫作課題' : '閱讀課題'}</>}</span><b>{unit.questions.length} 題</b></div><h3>{topic}</h3><p>{unit.title}・{objective}</p><small>{launchBattle ? '全班合力開戰' : completed ? `${completed} 題已完成` : activityMode === 'team-battle' ? '這題需個別操作' : '開始練習'} <ChevronRight size={15} /></small></button>;
}
export default function UnifiedChineseCatalog({ initialGrade = 'P1', onBack, onHome, completedUnits, onStartUnit }) {
  const [grade, setGrade] = useState(initialGrade); const [activityMode, setActivityMode] = useState('worksheet'); useEffect(() => { setGrade(initialGrade); }, [initialGrade]); const catalog = chineseCatalog[grade]; const bank = getChineseQuestionBank(grade); const questionCount = bank.units.reduce((total, unit) => total + unit.questions.length, 0); const lowPrimary = ['P1', 'P2', 'P3'].includes(grade);
  return <main className="site-shell catalog-page unified-catalog-page chinese-unified-page"><header className="topbar"><Brand /><div className="topbar-right"><span className="demo-pill">中文・P1–P6</span><button className="text-button" onClick={onBack}><ArrowLeft size={17} /> 返回選科</button><button className="icon-button" onClick={onHome} aria-label="返回首頁"><LayoutDashboard size={20} /></button></div></header><section className="subject-catalog-hero chinese-hero"><div><span className="kicker"><BookOpen size={15} /> 中文課題</span><h1>{catalog.gradeLabel} 中文</h1><p>{catalog.focus}</p></div><strong>{questionCount} 題</strong></section><section className="catalog-workbench unified-workbench chinese-workbench"><aside className="catalog-grade-rail"><span>年級</span>{GRADES.map((item, index) => <button className={grade === item ? 'active' : ''} onClick={() => { setGrade(item); setActivityMode('worksheet'); }} key={item}><b>{item}</b><small>小{GRADE_LABELS[index]}</small></button>)}</aside><div className="catalog-content unified-catalog-content"><div className="subject-grade-heading"><span>{grade}・課題與練習</span><h2>{activityMode === 'team-battle' ? '選擇合力題組，開始打怪獸。' : '選擇課題，直接開始練習。'}</h2></div>{lowPrimary && <section className="low-primary-battle-mode"><div><span><Swords size={16} /> 低小課堂遊戲</span><b>先選模式，再開啟單元</b><small>全班打怪獸會把可選答題目轉為投影合作挑戰。</small></div><div><button className={activityMode === 'worksheet' ? 'active' : ''} onClick={() => setActivityMode('worksheet')}>一般互動</button><button className={activityMode === 'team-battle' ? 'active battle' : ''} onClick={() => setActivityMode('team-battle')}><Swords size={15} /> 全班打怪獸</button></div></section>}<section className="subject-topic-grid">{bank.units.map((unit) => <TopicCard key={unit.id} unit={unit} grade={grade} catalog={catalog} completedUnits={completedUnits} onStart={onStartUnit} activityMode={activityMode} />)}</section></div></section></main>;
}
